# Generated by Django 5.1 on 2024-09-09 23:32

import utils.fileutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.fileutils.get_user_directory_path),
        ),
    ]
